---

- name: apt update
  apt: update_cache=yes
#  sudo: yes

- name: install git
  apt: pkg=git-core

- name: install pip
  apt: pkg=python-pip state=present
#  sudo: yes

- name: install python-pycurl
  apt: pkg=python-pycurl state=present
#  sudo: yes

- name: add-apt-repository -y ppa:chris-lea/node.js
  apt_repository: repo='ppa:chris-lea/node.js' state=present
#  sudo: yes

- name: "aptitude -y install nodejs"
  apt: pkg=nodejs state=present
#  sudo: yes
